#!/bin/sh

t0 () {
	out="$1"
	tee "$out"
	if ! test -s "$out"
	then
		rm "$out"
	fi
}

out="$1"
shift
gcc \
	-Wall \
	-Wextra \
	-g \
	-pthread \
	-O3 \
	-o "$out" "$@" \
	-lpcap -lssl -lcrypto -lpng 2>&1 | t0 "$out".err
